### ISSUE TITLE
Updating an asset version renders it null in referenced entries until they are republished

### ISSUE THREAD

**Issue by Chaitrasaurav** [contentstack/datasync-content-store-filesystem#15]
Hello,

We're encountering an issue with asset publishing. When a new asset version is published, the referenced entries don't get updated unless each entry is individually republished. This behaviour is traced back to the code at [https://github.com/contentstack/datasync-content-store-filesystem/blob/e8b75520d019819d1b5f879edd15cab150433921/src/fs.ts#L190]. We're puzzled about why publishing a new version essentially unpublishes the asset, deleting references without updating them.

Furthermore, even if we republish the same version, the entries still need manual republishing. This becomes burdensome as assets are referenced in numerous entries. Could you investigate and provide insights into why this unpublishing occurs?

Just an additional information, We have DataSync in-between our web and Contentstack. We do not call Contentstack API directly.

Regards,
Chaitra

**Comment by antonyagustine** [comment]
Hi @Chaitrasaurav,

Thank you for highlighting this matter. We will conduct an investigation into the issue.

**Comment by aman19K** [comment]
Hi @Chaitrasaurav ,
We have fixed and released this on production. Please update version to datasync-boilerplate v1.2.9.

`preserveAssetInReferencedEntries: false  `   
By default flag will be disabled so Updating an asset version renders it null in referenced entries until they are republished.
   
`preserveAssetInReferencedEntries: true    `
updating as asset version won't renders referenced entries with null(preserve asset uid in all referenced entries).

Using config, you can change that. Please check out the example settings for development and production.
